### ISSUE TITLE
Client-Side getTankInfo for EnderTank

### ISSUE THREAD

**Issue by hilburn** [Chicken-Bones/EnderStorage#34]
Querying getTankInfo on in a client side method returns a null fluid (new FluidStack(0,0)) - somewhere on client side you have access to the fluid for rendering purpose so could you modify the method to return the correct (or at least a valid) fluid

**Comment by Chicken-Bones** [comment]
The clients only receive their tank info when they're being looked at. I suppose I could say it has 0 water in it, but you shouldn't be asking for that info on the client anyway.

**Comment by hilburn** [comment]
I'd really rather not be working from client side either but I don't really have a choice about that - the method calling it is client side only so unless I was to do some message handling and data caching which is not really optimal...
Is the frequency available clientside? I could just display that instead of the contents of EnderStorage stuff

**Comment by Chicken-Bones** [comment]
It would appear that I do have the required info on the client side. Notice
that the clients interpolate the server, so do you want what's rendered, or
what the server says it has (eg change the frequency and it'll immediately
have the new liquid, but you'll see an animation on the client)

**Comment by hilburn** [comment]
Preferably what the server says it has.
Thanks a million

**Comment by Chicken-Bones** [comment]
Here you go dce6dbfd7644f8986624c0d579e81b2336522bb8 (1.7.10-1.4.5.30)

**Comment by hilburn** [comment]
honestly can't tell what's the fix and what's refactoring, but super :)

**Comment by Chicken-Bones** [comment]
Yeah sorry about that, just find the getTankInfo method

**Comment by psouza4** [comment]
Was this commit rolled into a release?

Simply viewing the tank in NotEnoughItems or via creative mode tabs will cause a crash with 1.4.6.31, the latest available download, complaining about a null fluid stack:

[21:51:44] [Client thread/WARN] [FML/]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[21:51:44] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:28)
[21:51:44] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
[21:51:44] [Client thread/WARN] [FML/]: *  at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.getLiquid(TankSynchroniser.java:225)
[21:51:44] [Client thread/WARN] [FML/]: *  at codechicken.enderstorage.storage.liquid.TankSynchroniser.getClientLiquid(TankSynchroniser.java:264)
[21:51:44] [Client thread/WARN] [FML/]: *  at codechicken.enderstorage.common.ItemEnderStorageRenderer.renderItem(ItemEnderStorageRenderer.java:48)
[21:51:44] [Client thread/WARN] [FML/]: *  at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)...
[21:51:44] [Client thread/WARN] [FML/]: ****************************************

Thoughts?

**Comment by Chicken-Bones** [comment]
Yeah, it was, that's a different bug which has since been fixed
