### ISSUE TITLE
NEI Crash with EnderTanks (v1.4.5.27)

### ISSUE THREAD

**Issue by vanceza** [Chicken-Bones/EnderStorage#51]
When the enderstorage section scrolls onto NEI, I see this, which I suspect is being caused by some interaction between NEI and EnderTanks. I see the bug in both SMP and singleplayer.

        [15:03:19] [Server thread/WARN] [FML]: ****************************************
        [15:03:19] [Server thread/WARN] [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
        [15:03:19] [Server thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
        [15:03:19] [Server thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
        [15:03:19] [Server thread/WARN] [FML]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18)
        [15:03:19] [Server thread/WARN] [FML]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28)
        [15:03:19] [Server thread/WARN] [FML]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20)
        [15:03:19] [Server thread/WARN] [FML]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35)...
        [15:03:19] [Server thread/WARN] [FML]: ****************************************
        [15:03:19] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ES
        java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
                at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
                at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
                at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18) ~[ExtendedFluidTank.class:?]
                at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28) ~[ExtendedFluidTank.class:?]
                at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20) ~[EnderLiquidStorage$Tank.class:?]
                at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35) ~[EnderLiquidStorage.class:?]
                at codechicken.enderstorage.storage.EnderLiquidStoragePlugin.createEnderStorage(EnderLiquidStoragePlugin.java:17) ~[EnderLiquidStoragePlugin.class:?]
                at codechicken.enderstorage.api.EnderStorageManager.getStorage(EnderStorageManager.java:161) ~[EnderStorageManager.class:?]
                at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:170) ~[TankSynchroniser$PlayerItemTankCache.class:?]
                at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:232) ~[TankSynchroniser$PlayerItemTankCache.class:?]
                at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
                at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:20) ~[EnderStorageSPH.class:?]
                at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
                at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
                at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
                at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
                at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
                at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
                at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
                at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
                at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
                at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
                at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
                at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
                at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
                at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

Versions
------

Minecraft: 1.7.10
Forge: 10.13.3.1408
CodeChickenCore-1.7.10-1.0.3.28-universal.jar
NotEnoughItems-1.7.10-1.0.3.60-universal.jar
(Minetweaker 3 and various other mods loaded but not mentioned in the stacktrace, if you can't reproduce I'll whittle down the mods to just these two)

**Comment by Chicken-Bones** [comment]
Update EnderStorage and CodeChickenCore

**Comment by vanceza** [comment]
Oops, didn't notice there was a 'latest' as well as 'recommended', despite reading the other reports of this. I'm dumb.
