### ISSUE TITLE
Scrolling through NEI crashes

### ISSUE THREAD

**Issue by Tim020** [Chicken-Bones/EnderStorage#54]
Not entirely sure why this is happening, but here is the relevant part of the log: 

[14:27:08] [Client thread/INFO] [FML]: InvTweaks: codechicken.enderstorage.storage.item.ContainerEnderItemStorage
[14:27:08] [Server thread/WARN] [FML]: ****************************************
[14:27:08] [Server thread/WARN] [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[14:27:08] [Server thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[14:27:08] [Server thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[14:27:08] [Server thread/WARN] [FML]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18)
[14:27:08] [Server thread/WARN] [FML]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28)
[14:27:08] [Server thread/WARN] [FML]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20)
[14:27:08] [Server thread/WARN] [FML]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35)...
[14:27:08] [Server thread/WARN] [FML]: ****************************************
[14:27:08] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel ES
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:?]
	at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18) ~[ExtendedFluidTank.class:?]
	at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28) ~[ExtendedFluidTank.class:?]
	at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20) ~[EnderLiquidStorage$Tank.class:?]
	at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35) ~[EnderLiquidStorage.class:?]
	at codechicken.enderstorage.storage.EnderLiquidStoragePlugin.createEnderStorage(EnderLiquidStoragePlugin.java:17) ~[EnderLiquidStoragePlugin.class:?]
	at codechicken.enderstorage.api.EnderStorageManager.getStorage(EnderStorageManager.java:161) ~[EnderStorageManager.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:170) ~[TankSynchroniser$PlayerItemTankCache.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:232) ~[TankSynchroniser$PlayerItemTankCache.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
	at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:20) ~[EnderStorageSPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.processPacket(FMLProxyPacket.java:86) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]

**Comment by Tim020** [comment]
Update fixed this
