### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by KasperFranz** [Chicken-Bones/EnderStorage#65]
```java.lang.NullPointerException: Exception in server tick loop
        at codechicken.lib.packet.PacketCustom.sendToPlayer(PacketCustom.java:496)
        at codechicken.lib.packet.PacketCustom.sendToPlayer(PacketCustom.java:489)
        at codechicken.enderstorage.internal.EnderStorageSPH.sendOpenUpdateTo(EnderStorageSPH.java:29)
        at codechicken.enderstorage.storage.EnderItemStoragePlugin.sendClientInfo(EnderItemStoragePlugin.java:42)
        at codechicken.enderstorage.api.EnderStorageManager.sendClientInfo(EnderStorageManager.java:84)
        at codechicken.enderstorage.api.EnderStorageManager.access$100(EnderStorageManager.java:26)
        at codechicken.enderstorage.api.EnderStorageManager$EnderStorageSaveHandler.onPlayerChangedDimension(EnderStorageManager.java:49)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_280_EnderStorageSaveHandler_onPlayerChangedDimension_PlayerLoggedOutEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:576)
        at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:439)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:956)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:166)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671)
        at java.lang.Thread.run(Unknown Source)
```
It is running the latest Infinity server which is running the latest version of your mod, it is however running on KCauldron, but there is nothing in the stacktrace about Kcauldron

**Comment by mrdeadlocked** [comment]
I had this same issue last night. I'll try to get with my users who were online and see whatmight have caused it.

**Comment by KasperFranz** [comment]
As far as i know it is when some users open a ender bag, not sure when he did it

**Comment by cauliflower69** [comment]
Just got the same error here when a player was extracting items out of an enderchest into AE system

**Comment by KaiKikuchi** [comment]
https://github.com/Chicken-Bones/CodeChickenLib/blob/1.7/src/codechicken/lib/packet/PacketCustom.java#L496

I think "playerNetServerHandler" is null. Maybe a null check at L496 will fix this issue.
    else if (((EntityPlayerMP) player).playerNetServerHandler != null)

**Comment by KaiKikuchi** [comment]
My build fixes this issue, hopefully.
https://github.com/KaiKikuchi/CodeChickenLib/releases/tag/v.1.1.3.138-KaiFix1

**Comment by devryb** [comment]
Working on Infinity 2.1.3, Direwolf20 1.9.0, Tekkit Legends 1.1.0 (Need to copy custom packet class files out)

**Comment by felipeleite5w** [comment]
hi, I know this topic has years, but kaifix it not working on my server, players need to use the kai fix? or only server-side? @KaiKikuchi

**Comment by KaiKikuchi** [comment]
> hi, I know this topic has years, but kaifix it not working on my server, players need to use the kai fix? or only server-side? @KaiKikuchi

Sorry, I do not remember and I do not have the files nor the server anymore!
